### ISSUE TITLE
Create GET /user/:user_id/borrowed_books route

### ISSUE THREAD

**Issue by actyralf** [taktsoft-campus-talents/delphine-project-week-library#35]

**Comment by Ladan-Mirzaei** [comment]
const objBooks = [
    { title: "Book 1", quantity: 5 },
    { title: "Book 2", quantity: 3 },
    { title: "Book 3", quantity: 7 },
  ];

  const objQuantityBorrowed = [
    { quantity: 2 },
    { quantity: 1 },
    { quantity: 4 },
  ];
